# Generated by Django 2.1.4 on 2019-03-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songsite', '0002_auto_20190223_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
